### ISSUE TITLE
vector-0.1.0.2 release violates PVP

### ISSUE THREAD

**Issue by phadej** [ocramz/vector-fft#2]
`vector-0.1.0.2` added a new export

```dif
@@@ Data.Vector.FFT
++ crossCorrelation :: Vector (Complex Double) -> Vector (Complex Double) -> Vector (Complex Double)
```

Yet, [PVP](https://pvp.haskell.org/) requires:

> *Non-breaking change.* Otherwise, if only new bindings, types, classes, non-orphan instances or modules (but see below) were added to the interface, then A.B **MAY** remain the same but the new C **MUST** be greater than the old C.

---

Please be careful with versioning. I don't think you need to do anything now. Feel free to close this issue when you see it.

**Comment by ocramz** [comment]
Thanks for letting me know!
